apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-local
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevOps local application deployments
  sourceRepos:
    - "*"
  destinations:
    - namespace: "!default"
      server: https://kubernetes.default.svc
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
