apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cd
  namespace: argo
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: local
  template:
    metadata:
      name: argocd-{{`{{ metadata.labels.environment }}`}}
    spec:
      destination:
        namespace: argocd
        server: "{{`{{ server }}`}}"
      project: devops-core-apps-{{`{{ metadata.labels.environment }}`}}
      sources:
        - chart: argo-cd
          helm:
            releaseName: argo-cd
            valueFiles:
              - $values/values/argocd/values.yaml
              - $values/values/argocd/values.{{`{{ metadata.labels.environment }}`}}.yaml
          repoURL: https://argoproj.github.io/argo-helm
          targetRevision: 8.0.0
        - repoURL: { { .Values.spec.repoUrl } }
          targetRevision: HEAD
          ref: values
